name: Keep Streamlit Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit
        run: curl -L https://genniacqcxj6xbjrk9niak.streamlit.app/
